function Test1()
{
  TestedApps.Patient_Files.Run(1, true);
  let patient_Files = Aliases.Patient_Files;
  let chooseRTDB = patient_Files.ChooseRTDB;
  chooseRTDB.UserList.ClickItem("My Patient6.0 (Desktop Only)");
  chooseRTDB.DBList.ClickItem("rmPatientFiles");
  let databaseListView = patient_Files.DatabaseListView;
  let MDIClient = databaseListView.MDIClient;
  let TDBListView = MDIClient.DBListView;
  TDBListView.Panel1.NewButton.ClickButton();
  let formLoadForm = MDIClient.FormLoadForm;
  OCR.Recognize(formLoadForm.TAdvPicture2).BlockByText("Personal").Click();
  let memo = formLoadForm.TMemo;
  memo.Click(189, 19);
  memo.Keys("[BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS][BS]Naresh");
  memo = formLoadForm.TMemo2;
  memo.Click(126, 19);
  memo.Keys("Green Valley");
  let panel = formLoadForm.TPanel;
  panel.Click(77, 14);
  panel.PopupMenu.Click("Choose Date");
  let popupCalendarForm = patient_Files.PopupCalendarForm;
  popupCalendarForm.DatePicker.wDate = "2020-08-01";
  popupCalendarForm.OKButton.ClickButton();
  panel = formLoadForm.TPanel2;
  panel.Click(31, 11);
  panel.PopupMenu.Click(" B +");
  memo = formLoadForm.TMemo3;
  memo.Click(205, 1);
  memo.Click(200, 12);
  memo.Keys("Babu");
  panel = formLoadForm.TPanel3;
  panel.Click(41, 17);
  panel.PopupMenu.Click("Male");
  panel = formLoadForm.TPanel4;
  panel.Click(16, 14);
  panel.PopupMenu.Click("No Value");
  memo = formLoadForm.TMemo4;
  memo.Click(91, 11);
  memo.Keys("454548451");
  memo = formLoadForm.TMemo5;
  memo.Click(65, 10);
  memo.Keys("5454484848");
  memo = formLoadForm.TMemo6;
  memo.Click(22, 15);
  memo.Keys("medicine@gmail.com");
  panel = formLoadForm.TPanel5;
  panel.Click(5, 11);
  panel.Click(13, 4);
  panel.PopupMenu.Click("Student");
  memo = formLoadForm.TMemo7;
  memo.DblClick(28, 7);
  memo.Keys("1");
  formLoadForm.TAdvPicture.Drag(89, 61, -1, 230);
  formLoadForm.Drag(773, 764, -13, -226);
  databaseListView.Drag(371, 17, 178, 163);
  databaseListView.Maximize();
  formLoadForm.TImage.Click(73, 14);
  panel = formLoadForm.TPanel6;
  OCR.Recognize(panel).BlockByText("Ok").Click();
  let advStringGrid = TDBListView.Grid;
  advStringGrid.HScroll.Pos = 0;
  advStringGrid.VScroll.Pos = 127;
  advStringGrid.ClickR(35, 113);
  advStringGrid.ClickR(53, 112);
  advStringGrid.Click(15, 115);
  panel.Click(31, 5);
  aqObject.CheckProperty(Aliases.Patient_Files.DatabaseListView.MDIClient.DBListView.Grid, "wValue(1, 1)", cmpEqual, "Naresh");
}